# index:
#    path: /
#    controller: App\Controller\DefaultController::index

logout:
    path: /logout

# app/config/routing.yml
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml"